cards/urls.py
from django.urls import path
from . views import add_card,view_card,add_chat,CalendarView

urlpatterns = [
    path('add_card/',add_card,name='add_card'),
    path('add_chat/<int:cid>/',add_chat,name='add_chat'),
    path('view_card/<int:cid>/',view_card,name='view_card'),
    path('calendar/',CalendarView.as_view(),name='calendar')

]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('auth1.urls')),
    path('card/',include('cards.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cards/models.py
from django.db import models

# Create your models here.

class Cards(models.Model):              #Database structure of the cards
    c_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, blank=True, unique=True)
    description = models.TextField(max_length=100, blank=True)
    due = models.DateField(null=True, blank=True)
    assigned = models.CharField(max_length=50, blank=True)
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.title +':'+ str(self.c_id)

class Chat(models.Model):               #Database structure of the chats
    msg = models.CharField(max_length=50, blank=True)
    author = models.CharField(max_length=50, blank=True)
    card = models.ForeignKey('Cards',on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    file = models.FileField(null=True, blank=True)


    def __str__(self):
        return str(self.card) +"-->"+ str(self.msg)

cards/forms.py
from django import forms
from bootstrap_datepicker_plus import DatePickerInput
from .models import Cards,Chat

class NewCard(forms.ModelForm):
	class Meta:
		model = Cards
		fields = ['title','description','due','assigned','file']
		widgets = {
            'due': DatePickerInput(), # specify date-frmat
        }

class NewChat(forms.ModelForm):
	class Meta:
		model = Chat
		fields = ['author','msg','file','card']

cards/views.py
from django.shortcuts import render,redirect
from django.views import generic
from datetime import datetime, timedelta, date
from datetime import datetime
from . forms import NewCard,NewChat
from django.http import HttpResponse
from .utils import Calendar
from django.utils.safestring import mark_safe
from . models import Cards,Chat
import calendar
# Create your views here.

def add_card(request):
	# print (request)
	form = NewCard(request.POST or None,request.FILES or None)     #POST request to retrieve the data with the file if any
	if form.is_valid():
		form.save()

	context = {'form': form}
	return render(request,'add_cards.html',context)    #sends the form to retieve the card data

def view_card(request,cid):
	card = Cards.objects.filter(c_id=cid).first()      #c_id is passed to identify the card which is used to filter through the DB 
	chat = Chat.objects.filter(card__c_id=cid).order_by('id')      #the same c_id is used to filter through the chat as well
	if card != None:
		return render(request,'card.html',{'card':card,'chat':chat})      #page is rendered with the card and it's corresponding chat
	else:
		return HttpResponse("Nopidy nope")        #c_id is invalid

def add_chat(request,cid):
# print (request)
    form = NewChat(request.POST or None,request.FILES or None)      #POST request to retrieve the data with the file if any
    if form.is_valid():
        print (form)
        form.save()

    context = {'form': form,'cid':cid}
    return render(request,'add_chat.html',context)      #sends the form to retieve the card data

class CalendarView(generic.ListView):
    model = Cards       #retireves the cards data from the DB
    template_name = 'calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

cards/templates/add_cards.html
{%  extends 'base.html' %}
{% block content %}
{% load bootstrap4 %} 
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %} 
{% if user.is_authenticated and user.profile.admin %}
<style type="text/css">
	.grid-container {
	  display: grid;
	  grid-template-areas:
	    'main right';
	  grid-gap: 10px;
	}

</style>
<div style="width: 50%; padding-left:10%; padding-top: 5px ">
	<div class="grid-container">
		<form method="POST" enctype="multipart/form-data">
		<div class="main" style="color: white;">
			{% csrf_token %}
			{{ form.media }}
		    {% bootstrap_form form %}
	    </div>
	    <div class="right">
			<input style="position: absolute; left:50%;  bottom: 30px;" type="submit" value='Save' />
		</div>	
		</form>
	</div>
</div>
{% else %}
<h1>GET OUT!!</h1>
{% endif %}
{% endblock%}

cards/templates/add_chat.html
{%  extends 'base.html' %}
{% block content %}
{% load bootstrap4 %} 
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %} 
{% if user.is_authenticated and user.profile.member or user.profile.admin %}
<style type="text/css">
    body {
      background-image: url(https://wallpaperplay.com/walls/full/e/7/3/63371.jpg);
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100% 100%;
    }
</style>
<div style="width: 50%; padding-left:10%; padding-top: 50px ">
<form method="POST" enctype="multipart/form-data" >
  {% csrf_token %}
<div class="form-group">
  <label for="id_author">Author</label>
  <input type="text" value="{{user.username}}" name="author" maxlength="50" class="form-control" placeholder="Author" title="" id="id_author" readonly>
</div>
<div class="form-group">
  <label for="id_msg">Msg</label>
  <input type="text" name="msg" maxlength="50" class="form-control" placeholder="Msg" title="" id="id_msg">
</div>
<div class="form-group">
  <label for="id_card">Card</label>
  <select name="card" class="form-control" title="" required id="id_card" readonly>
    <option value="{{cid}}" selected>Card:{{cid}}</option>
  </select>
</div>    
<div class="form-group">
  <label for="id_file">File</label>
  <input type="file" name="file" class="form-control-file" title="" id="id_file">
</div>

  <input type="submit" value='Save' />

</form>
<div><a href="//localhost:8000/card/view_card/{{cid}}/"> Back</a></div>
</div>
{% else %}
<h1>GET OUT!!</h1>
{% endif %}
{% endblock%}

cards/templates/base.html
<!-- cal/templates/cal/base.html -->

{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{'% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
  <style type="text/css">
    .calendar {
      width: 98%;
      margin: auto;
      font-size: 13px;
    }

    .calendar tr, .calendar td {
      border: 1px solid black;
    }

    .calendar th {
      padding: 10px;
      text-align: center;
      font-size: 18px;
    }

    .calendar td {
      width: 200px;
      height: 150px;
      padding: 20px 0px 0px 5px;
    }

    .month {
      font-size: 25px;
    }

    .date {
      font-size: 16px;
    }

    ul {
      height: 100%;
      padding: 0px 5px 0px 20px;
    }

    a {
      color: #17a2b8;
    }
  
  </style>
</head>
<body>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

cards/templates/calendar.html
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <style type="text/css">

      body {
      background-image: url(https://wallpaperplay.com/walls/full/0/1/8/33407.jpg);
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100% 100%;
    }
    
    .calendar {
      width: 98%;
      margin: auto;
      font-size: 13px;
    }

    .calendar tr, .calendar td {
      border: 1px solid black;
    }

    .calendar th {
      padding: 10px;
      text-align: center;
      font-size: 18px;
    }

    .calendar td {
      width: 80px;
      height: 50px;
      padding: 20px 0px 0px 5px;
    }

    .month {
      font-size: 25px;
    }

    .date {
      font-size: 16px;
    }

    ul {
      height: 100%;
      padding: 0px 5px 0px 20px;
    }

    a {
      color: #17a2b8;
    }
    .left {
      float: left;
    }

    .right {
      float: right;
    }

    .centr{
      margin-left: 40%;
    }

    .btn {
      outline: none;
      color: black;
      background-color: transparent;
      box-shadow: 0 0 0 0;
    }

    .clearfix {
      margin: 15px;
    }
  </style>
</head>
<body>
{% if user.is_authenticated and user.profile.member or user.profile.admin %}

{% block content %}

<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendar' %}?{{ prev_month }}"> Previous Month </a>
  <a class="btn btn-info centr" href="http://localhost:8000"> Home Page </a>
  <a class="btn btn-info right" href="{% url 'calendar' %}?{{ next_month }}"> Next Month </a>
</div>

{{ calendar }}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
{% else %}
<h1>GET OUT!!</h1>
{% endif %}

</body>
</html>

cards/templates/card.html
{%  extends 'base.html' %}
{% block content %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,700" rel="stylesheet">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css'>
<style type="text/css">
	/*PEN STYLES*/
* {
  box-sizing: border-box;
}

  body {
      background-image: url(https://wallpaperplay.com/walls/full/e/7/3/63371.jpg);
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100% 100%;
    }

.blog-card {
  display: -webkit-box;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
          flex-direction: column;
  margin: 1rem auto;
  box-shadow: 0 3px 7px -1px rgba(0, 0, 0, 0.1);
  margin-bottom: 1.6%;
  background: #fff;
  line-height: 1.4;
  font-family: sans-serif;
  border-radius: 5px;
  overflow: hidden;
  z-index: 0;
}
.blog-card a {
  color: inherit;
}
.blog-card a:hover {
  color: #5ad67d;
}
.blog-card:hover .photo {
  -webkit-transform: scale(1.3) rotate(3deg);
          transform: scale(1.3) rotate(3deg);
}
.blog-card .meta {
  position: relative;
  z-index: 0;
  height: 200px;
}
.blog-card .photo {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-size: cover;
  background-position: center;
  -webkit-transition: -webkit-transform .2s;
  transition: -webkit-transform .2s;
  transition: transform .2s;
  transition: transform .2s, -webkit-transform .2s;
}
.blog-card .details,
.blog-card .details ul {
  margin: auto;
  padding: 0;
  list-style: none;
}
.blog-card .details {
  position: absolute;
  top: 0;
  bottom: 0;
  left: -100%;
  margin: auto;
  -webkit-transition: left .2s;
  transition: left .2s;
  background: rgba(0, 0, 0, 0.6);
  color: #fff;
  padding: 10px;
  width: 100%;
  font-size: .9rem;
}
.blog-card .details a {
  -webkit-text-decoration: dotted underline;
          text-decoration: dotted underline;
}
.blog-card .details ul li {
  display: inline-block;
}
.blog-card .details .author:before {
  font-family: FontAwesome;
  margin-right: 10px;
  content: "\f007";
}
.blog-card .details .date:before {
  font-family: FontAwesome;
  margin-right: 10px;
  content: "\f133";
}
.blog-card .details .tags ul:before {
  font-family: FontAwesome;
  content: "\f02b";
  margin-right: 10px;
}
.blog-card .details .tags li {
  margin-right: 2px;
}
.blog-card .details .tags li:first-child {
  margin-left: -4px;
}
.blog-card .description {
  padding: 1rem;
  background: #fff;
  position: relative;
  z-index: 1;
}
.blog-card .description h1,
.blog-card .description h2 {
  font-family: Poppins, sans-serif;
}
.blog-card .description h1 {
  line-height: 1;
  margin: 0;
  font-size: 1.7rem;
}
.blog-card .description h2 {
  font-size: 1rem;
  font-weight: 300;
  text-transform: uppercase;
  color: #a2a2a2;
  margin-top: 5px;
}
.blog-card .description .read-more {
  text-align: right;
}
.blog-card .description .read-more a {
  color: #5ad67d;
  display: inline-block;
  position: relative;
}
.blog-card .description .read-more a:after {
  content: "\f061";
  font-family: FontAwesome;
  margin-left: -10px;
  opacity: 0;
  vertical-align: middle;
  -webkit-transition: margin .3s, opacity .3s;
  transition: margin .3s, opacity .3s;
}
.blog-card .description .read-more a:hover:after {
  margin-left: 5px;
  opacity: 1;
}
.blog-card p {
  position: relative;
  margin: 1rem 0 0;
}
.blog-card p:first-of-type {
  margin-top: 1.25rem;
}
.blog-card p:first-of-type:before {
  content: "";
  position: absolute;
  height: 5px;
  background: #5ad67d;
  width: 35px;
  top: -0.75rem;
  border-radius: 3px;
}
.blog-card:hover .details {
  left: 0%;
}
@media (min-width: 640px) {
  .blog-card {
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
            flex-direction: row;
    max-width: 90%;
  }
  .blog-card .meta {
    flex-basis: 40%;
    height: auto;
  }
  .blog-card .description {
    flex-basis: 60%;
  }
  .blog-card .description:before {
    -webkit-transform: skewX(-3deg);
            transform: skewX(-3deg);
    content: "";
    background: #fff;
    width: 30px;
    position: absolute;
    left: -10px;
    top: 0;
    bottom: 0;
    z-index: -1;
  }
  .blog-card.alt {
    -webkit-box-orient: horizontal;
    -webkit-box-direction: reverse;
            flex-direction: row-reverse;
  }
  .blog-card.alt .description:before {
    left: inherit;
    right: -10px;
    -webkit-transform: skew(3deg);
            transform: skew(3deg);
  }
  .blog-card.alt .details {
    padding-left: 25px;
  }
}
</style>

</head>
<body>
<!-- partial:index.partial.html -->
{% if user.is_authenticated and user.profile.member or user.profile.admin %}
  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://source.unsplash.com/1600x900/?technology)"></div>
      <ul class="details">
        <li class="author"><a href="#">{{card.assigned}}</a></li>
        <li class="date">{{card.due}}</li>
       <!--  <li class="tags">
          <ul>
            <li><a href="#">Learn</a></li>
            <li><a href="#">Code</a></li>
            <li><a href="#">HTML</a></li>
            <li><a href="#">CSS</a></li>
          </ul>
        </li> -->
      </ul>
    </div>
    <div class="description">
      <h1>{{card.title}}</h1>
      <h2>To : {{card.assigned}} &nbsp&nbsp&nbsp By : {{card.due}} &nbsp&nbsp&nbsp <a href="/media/{{card.file}}" download>File: {{card.file}}</a></h2>
      <h3>{{card.description}}</h3>
      {% for c in chat%}
              <p><b>{{c.author}}</b><a style="font-size: 10px;">({{c.created_at}})</a>:{{c.msg}} &nbsp&nbsp&nbsp 
                {% if c.file %}
                  Upload:<a href="/media/{{c.file}}" download>{{c.file}}</a></p>
                {% endif %}
      {% endfor %}
      <p class="read-more">
        <a href="http://localhost:8000/card/add_chat/{{card.c_id}}/">Add on</a>
      </p>
    </div>
  </div>

<!-- partial -->
{% else %}
<h1>GET OUT!!</h1>
{% endif %}
</body>
{% endblock%}